Имплементировано задание  task2
TarasKamenik/altexsoft-lab-2020 pull request #2
Opened 2020-08-20 19:02 UTC by TarasKamenik

2020-09-07 18:26 UTC, alex-geraschenko requested changes

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Data/UnitOfWork.cs
> +		private List<T> ResolveEntitiesFile<T>(string path, IList<T> entities)
Этот метод лучше разделить на 2: `Load` и `Save`

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Data/IUnitOfWork.cs
> +	public interface IUnitOfWork
Не хватает метода сохранения

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Controller/RecipeBookController.cs
> +								var category = _unitOfWork.CategoryRepository.GetCategory(id);
Чтобы не дублировать вызовы типа `_unitOfWork.CategoryRepository` лучше создать для каждого репозитория приватное поле и заполнить его в конструкторе. `_categoryRepository = _unitOfWork.CategoryRepository;`

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Repository/CategoryRepository.cs
> +			throw new NotImplementedException();
Почему метод не реализован?

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Data/IUnitOfWork.cs
> +		RecipeRepository RecipeRepository { get; set; }
Лучше использовать интерфейс, а не конкретный класс

2020-09-07 18:26 UTC, alex-geraschenko commented on task2/Repository/IngredientRepository.cs
> +			throw new NotImplementedException();
Почему метод не реализован?

2020-09-07 20:06 UTC, TarasKamenik commented on task2/Data/UnitOfWork.cs
> +		private List<T> ResolveEntitiesFile<T>(string path, IList<T> entities)
Не пойму а в чём смысл такого разделения?

2020-09-07 20:19 UTC, TarasKamenik commented on task2/Controller/RecipeBookController.cs
> +								var category = _unitOfWork.CategoryRepository.GetCategory(id);
Объясните пожалуйста в чём смысл создавать новые поля, чем это будет лучше?

2020-09-07 20:21 UTC, TarasKamenik commented on task2/Repository/CategoryRepository.cs
> +			throw new NotImplementedException();
Потому что нет логики сохранения для категорий по условию задачи.

2020-09-07 20:22 UTC, TarasKamenik commented on task2/Repository/IngredientRepository.cs
> +			throw new NotImplementedException();
Потому что нет логики сохранения для категорий по условию задачи.

2020-09-09 08:11 UTC, alex-geraschenko requested changes

2020-09-09 08:11 UTC, alex-geraschenko commented on task2/Repository/CategoryRepository.cs
> +			throw new NotImplementedException();
Условие задачи не обязывало сохранять категории, но и не запрещало. Если не хотите реализовывать сохранение, то нужно поменять структур классов так, чтобы не было таких исключений, иначе это нарушение принципа **Liskov Substitution**.

2020-09-09 08:11 UTC, alex-geraschenko commented on task2/Data/UnitOfWork.cs
> +		private List<T> ResolveEntitiesFile<T>(string path, IList<T> entities)
Смысл в том, что метод должен выполнять одну задачу

2020-09-09 08:11 UTC, alex-geraschenko commented on task2/Repository/IngredientRepository.cs
> +			throw new NotImplementedException();
Условие задачи не обязывало сохранять ингридиенты, но и не запрещало. Если не хотите реализовывать сохранение, то нужно поменять структур классов так, чтобы не было таких исключений, иначе это нарушение принципа **Liskov Substitution**.

2020-09-09 08:31 UTC, alex-geraschenko commented on task2/Controller/RecipeBookController.cs
> +								var category = _unitOfWork.CategoryRepository.GetCategory(id);
Чтобы не дублировать вызовы типа `_unitOfWork.CategoryRepository`. Код будет немного короче и читабельнее.
Вместо
```
var category = _unitOfWork.CategoryRepository.GetCategory(id);
```
будет
```
var category = _categoryRepository.GetCategory(id);
```

2020-09-10 09:09 UTC, alex-geraschenko requested changes

2020-09-10 09:09 UTC, alex-geraschenko commented on task2/Data/UnitOfWork.cs
> +		private static string _ingredientsFile = "ingredients.json";
Я бы лучше перенес имя файла внутрь репозитория. Например, через абстрактное свойство `FileName` в `GenericRepository`

2020-09-10 09:09 UTC, alex-geraschenko commented on task2/Data/UnitOfWork.cs
> +			var ingredientList = ResolveEntitiesFile(Path.Combine(storagePath, _ingredientsFile), inMemoryService?.GetAllIngredients());
Лучше перенести логику `ResolveEntitiesFile` внутрь репозитория и в конструктор репозитория передавать `inMemoryService`

2020-09-10 09:09 UTC, alex-geraschenko commented on task2/Repository/CategoryRepository.cs
> +		public override void Save()
Код метода `Save` дублируется во всех репозиториях. Лучше вынести его в `GenericRepository`

2020-09-10 09:09 UTC, alex-geraschenko commented on task2/Repository/IngredientRepository.cs
> +			var json = JsonSerializer.Serialize(Items);
Код метода `Save` дублируется во всех репозиториях. Лучше вынести его в `GenericRepository`

2020-09-10 09:09 UTC, alex-geraschenko commented on task2/Repository/RecipeRepository.cs
> +			var json = JsonSerializer.Serialize(Items);
Код метода `Save` дублируется во всех репозиториях. Лучше вынести его в `GenericRepository`

2020-09-12 20:36 UTC, TarasKamenik commented on task2/Data/UnitOfWork.cs
> +		private static string _ingredientsFile = "ingredients.json";
Но ведь репозитории не должны знать откуда беруться данные, будь то фаил база данных или что-то другое? Мне кажется это нарушило бы принципы SRP и OCP.

2020-09-12 20:50 UTC, TarasKamenik commented on task2/Data/UnitOfWork.cs
> +			var ingredientList = ResolveEntitiesFile(Path.Combine(storagePath, _ingredientsFile), inMemoryService?.GetAllIngredients());
Т.к. репозитории не должны знать о том как получаются данные логика по определению данных инкапсулирована в UnitOfwork, а InMemoryRepository нужен временно для инициализации данных, например когда будет подключена база данных его можно будет удалить. Поэтому я бы не хотел делать лишних зависимостей

2020-09-14 16:22 UTC, alex-geraschenko requested changes

2020-09-14 16:22 UTC, alex-geraschenko commented on task2/Data/UnitOfWork.cs
> +		private static string _ingredientsFile = "ingredients.json";
В таком случае имеет смысл создать отдельный FileManager, который будет отвечать за работу с файлами: определение имени файла по типу сущности, например: `$"{typeof(T).Name}.json";`, а также чтение из файа, запись в файл, `ResolveEntitiesFile`, `InitDataIfNotExist`

2020-09-21 18:23 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-09-24 19:26 UTC, merged